services:
  - type: web
    name: market-weather
    runtime: node
    plan: free
    region: oregon # or frankfurt, singapore, ohio
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: INITIAL_ADMIN_EMAIL
        value: admin@security.enterprise
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
